### ISSUE TITLE
ease-[] with custom value is being overshadowed by the plugin

### ISSUE THREAD

**Issue by louisgv** [jamiebuilds/tailwindcss-animate#48]
Ref: https://tailwindcss.com/docs/transition-timing-function

When using this plugin, `ease-[]` will not work as the plugin claimed all the `ease-*` utility.

**Comment by louisgv** [comment]
NVM, the custom value I used was invalid.

**Comment by ashugeo** [comment]
Actually I think this issue is valid!

I was having issues with `ease-[cubic-bezier(0.95,0.05,0.795,0.035)]` not being picked up  (example from [the Tailwind docs](https://tailwindcss.com/docs/transition-timing-function#arbitrary-values)).

I disabled `tailwindcss-animate` from the list of plugins in `tailwind.config.js` and that fixed it.

cc @jamiebuilds could this be re-opened? 🙂 (happy to re-create if you prefer)
